//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mark { get; set; }
        public byte[] Pic { get; set; }
        public Nullable<int> IDOwner { get; set; }
        public string IDCountry { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Person Person { get; set; }
    }
}
