//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public int ID { get; set; }
        public string BarCounter { get; set; }
        public Nullable<int> IDDrink { get; set; }
    
        public virtual Drink Drink { get; set; }
    }
}
